name: Makefile CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
      
    - name: Install
      run: npm ci

    - name: Using
      run: make setup
    - run: make start 

    - name: Run test
      run: make test

    - name: Run linter
      run: make lint
